mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from trips.views import hello_world
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('trips/',hello_world),
    path('api',include('trips.urls')),
    path('trips/', include('trips.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



trips/urls.py
# trips/urls.py
from django.urls import path
from .views import QuestionDetailAPIView, UserProfileCreateAPIView, PostUpdateAPIView
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.user_profile, name='user_profile'),  # Profile page URL (e.g., data entry)
    path('profile/manual/', views.manual, name='manual'),  # Manual page URL
    path('profile/manual/road/', views.road, name='road'),  # Road page URL
    path('profile/manual/road/route1/', views.route1, name='route1'),  # 添加这一行
    path('profile/manual/road/route2/', views.route2, name='route2'),  # 添加这一行
    path('profile/manual/road/route3/', views.route3, name='route3'),  # 添加这一行
    path('profile/manual/road/<int:number>/', views.profile_success, name='profile_success'),
    path('api/user/', UserProfileCreateAPIView.as_view(), name='user-create'),
    path('api/question/<int:question_id>/', QuestionDetailAPIView.as_view(), name='question-detail'),
    path('api/post/<str:phone>/', PostUpdateAPIView.as_view(), name='post-update'),
]







trips/models.py
from django.db import models

# Create your models here.
def default_content():
    return {
        "1": {
            "status": "null", # null, pass, fail
            "user_answer": "",
            "correct_answer": "",
        },
        "2": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "3": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "4": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "5": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "6": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "7": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "8": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "9": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "10": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "11": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "12": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "13": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "14": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "15": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "16": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "17": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "18": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "19": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "20": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "21": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "22": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "23": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "24": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "25": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "26": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "27": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "28": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
        "29": {
            "status": "null",
            "user_answer": "",
            "correct_answer": "",
        },
    }


class Question(models.Model):
    number = models.PositiveIntegerField(unique=True)
    batch = models.CharField(max_length=100)  # 梯次 第一天,第二天
    route = models.CharField(max_length=1)  #路線名稱 A,B,C
    title = models.CharField(max_length=100) #廠商名稱
    icon = models.URLField(blank=True) #廠商icon
    question = models.CharField(max_length=100) #題目
    choiceA = models.CharField(max_length=100) #選項
    choiceB = models.CharField(max_length=100)
    choiceC = models.CharField(max_length=100)
    choiceD = models.CharField(max_length=100)
    answer = models.CharField(max_length=100) #答案

    def __str__(self):
        return f"{self.number}. {self.question}"

class UserProfile(models.Model):
    GENDER_CHOICES = [
        ('M', '男'),
        ('F', '女'),
        ('O', '其他'),
    ]

    phone = models.CharField(max_length=15, primary_key=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)

    def __str__(self):
        return f"{self.get_gender_display()} - {self.phone}"

class Post(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.SET_NULL, related_name='post', null=True, blank=True)
    content = models.JSONField(default=default_content)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    update_at = models.DateTimeField(user)
    def __str__(self):
        return f"Post by {self.user.phone} at {self.created_at}"




# class Post1(models.Model):
#     number = models.PositiveIntegerField()
#     title = models.CharField(max_length=100)
#     content = models.TextField(blank=True)
#     image = models.ImageField(upload_to='questions/', blank=True, null=True)

#     def __str__(self):
#         return f"{self.number}. {self.title}"

trips/forms.py
from django import forms
from .models import UserProfile

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['gender', 'phone']
        widgets = {
            'gender': forms.RadioSelect(choices=UserProfile.GENDER_CHOICES)
        }

trips/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics, status
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Post , Question, UserProfile
from .serializers import QuestionSerializer, UserProfileSerializer, PostSerializer
from .forms import UserProfileForm

class QuestionDetailAPIView(APIView):

    def get_object(self, question_id):
        try:
            return Question.objects.get(number=question_id)
        except Question.DoesNotExist:
            return None

    def get(self, request, question_id, *args, **kwargs):
        question_instance = self.get_object(question_id)
        if not question_instance:
            return Response(
                {"res": "Object with question id does not exist"},
                status=status.HTTP_400_BAD_REQUEST
            )
        serializer = QuestionSerializer(question_instance)
        return Response(serializer.data, status=status.HTTP_200_OK)


class UserProfileCreateAPIView(APIView):
    def post(self, request, *args, **kwargs):
        serializer = UserProfileSerializer(data=request.data)
        if serializer.is_valid():
            user_profile = serializer.save()
            return Response(UserProfileSerializer(user_profile).data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class PostUpdateAPIView(APIView):
    def patch(self, request, phone,  *args, **kwargs):
        try:
            user_profile = UserProfile.objects.get(phone=phone)
        except UserProfile.DoesNotExist:
            return Response({"error": "User profile not found"}, status=status.HTTP_404_NOT_FOUND)

        serializer = PostSerializer(user_profile.post, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

def hello_world(request):
    return HttpResponse("Hello World!")

def index(request):
    return render(request, 'index.html')

class PostListCreate(generics.ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
# Create your views here.

def user_profile(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            form.save()
            # 表单成功后重定向到 manual 页面
            return redirect('manual')
    else:
        form = UserProfileForm()

    return render(request, 'user_profile.html', {'form': form})


def profile_success(request, number):
    question = get_object_or_404(Question, number=number)
    return render(request, 'profile_success.html', {'question': question})


def ar_scan01(request):
    return render(request, 'ar_scan01.html')

def manual(request):
    return render(request, 'manual.html')

def road(request):
    return render(request, 'road.html')

def route1(request):
    return render(request, 'route1.html')

def route2(request):
    return render(request, 'route2.html')

def route3(request):
    return render(request, 'route3.html')

trips/templates/ar_for_test copy.html
<!-- @Author: YI-SYUAN -->


<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="https://aframe.io/releases/1.6.0/aframe.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mind-ar@1.2.5/dist/mindar-image-aframe.prod.js"></script>
  </head>
  <body>
    <a-scene mindar-image="imageTargetSrc: ../mind/targets_00.mind;" color-space="sRGB" renderer="colorManagement: true, physicallyCorrectLights" vr-mode-ui="enabled: false" device-orientation-permission-ui="enabled: false">
      <a-assets>
        <img id="card1" src="../img/img_02.png" />
        <img id="card2" src="../img/img_03.png" />
        <img id="card3" src="../img/img_04.png" />
        <img id="card4" src="../img/img_05.png" />
        <img id="card5" src="../img/img_06.png" />
        <img id="card6" src="../img/img_07.png" />
        <img id="card7" src="../img/img_08.png" />
        <img id="card8" src="../img/img_09.png" />
        <img id="card9" src="../img/img_10.png" />
        <img id="card10" src="../img/img_11.png" />
        <img id="card11" src="../img/img_12.png" />
        <img id="card12" src="../img/img_13.png" />
        <img id="card13" src="../img/img_14.png" />
        <img id="card14" src="../img/img_15.png" />
        <img id="card15" src="../img/img_16.png" />
        <img id="card16" src="../img/img_17.png" />
        <img id="card17" src="../img/img_18.png" />
        <img id="card18" src="../img/img_19.png" />
        <img id="card19" src="../img/img_20.png" />
        <img id="card20" src="../img/img_21.png" />
        <img id="card21" src="../img/img_22.png" />
        <img id="card22" src="../img/img_23.png" />
        <img id="card23" src="../img/img_24.png" />
        <img id="card24" src="../img/img_25.png" />
        <img id="card25" src="../img/img_26.png" />
        <img id="card26" src="../img/img_27.png" />
        <img id="card27" src="../img/img_28.png" />
        <img id="card28" src="../img/img_29.png" />
        <!-- <a-asset-item id="avatarModel" src="https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/examples/image-tracking/assets/card-example/softmind/scene.gltf"></a-asset-item> -->
      </a-assets>

      <a-camera position="0 0 0" look-controls="enabled: false"></a-camera>
      <a-entity mindar-image-target="targetIndex: 0">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 1">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 2">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 3">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 4">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 5">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 6">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 7">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 8">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 9">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 10">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 11">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 12">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 13">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 14">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 15">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 16">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 17">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 18">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 19">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 20">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 21">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 22">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 23">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 24">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 25">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 26">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 27">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
      <a-entity mindar-image-target="targetIndex: 28">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
      </a-entity>
    </a-scene>
  </body>
</html>

trips/templates/ar_scan02.html
<!-- @Author: YI-SYUAN -->


<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="https://aframe.io/releases/1.6.0/aframe.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mind-ar@1.2.5/dist/mindar-image-aframe.prod.js"></script>
  </head>
  <body>
    <a-scene mindar-image="imageTargetSrc: ../mind/targets_002.mind;" color-space="sRGB" renderer="colorManagement: true, physicallyCorrectLights" vr-mode-ui="enabled: false" device-orientation-permission-ui="enabled: false">
      <a-assets>
        <img id="card" src="../img/img_002.png" />
        <a-asset-item id="avatarModel" src="https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/examples/image-tracking/assets/card-example/softmind/scene.gltf"></a-asset-item>
      </a-assets>

      <a-camera position="0 0 0" look-controls="enabled: false"></a-camera>
      <a-entity mindar-image-target="targetIndex: 0">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
        <!-- <a-gltf-model rotation="0 0 0 " position="0 0 0.1" scale="0.005 0.005 0.005" src="#avatarModel" animation="property: position; to: 0 0.1 0.1; dur: 1000; easing: easeInOutQuad; loop: true; dir: alternate"></a-gltf-model> -->
      </a-entity>
    </a-scene>
  </body>
</html>

trips/templates/ar_scan03.html
<!-- @Author: YI-SYUAN -->


<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="https://aframe.io/releases/1.6.0/aframe.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mind-ar@1.2.5/dist/mindar-image-aframe.prod.js"></script>
  </head>
  <body>
    <a-scene mindar-image="imageTargetSrc: ../mind/targets_03.mind;" color-space="sRGB" renderer="colorManagement: true, physicallyCorrectLights" vr-mode-ui="enabled: false" device-orientation-permission-ui="enabled: false">
      <a-assets>
        <img id="card" src="../img/img_03.png" />
        <a-asset-item id="avatarModel" src="https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/examples/image-tracking/assets/card-example/softmind/scene.gltf"></a-asset-item>
      </a-assets>

      <a-camera position="0 0 0" look-controls="enabled: false"></a-camera>
      <a-entity mindar-image-target="targetIndex: 0">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
        <!-- <a-gltf-model rotation="0 0 0 " position="0 0 0.1" scale="0.005 0.005 0.005" src="#avatarModel" animation="property: position; to: 0 0.1 0.1; dur: 1000; easing: easeInOutQuad; loop: true; dir: alternate"></a-gltf-model> -->
      </a-entity>
    </a-scene>
  </body>
</html>

trips/templates/ar_scan04.html
<!-- @Author: YI-SYUAN -->


<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="https://aframe.io/releases/1.6.0/aframe.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mind-ar@1.2.5/dist/mindar-image-aframe.prod.js"></script>
  </head>
  <body>
    <a-scene mindar-image="imageTargetSrc: ../mind/targets_04.mind;" color-space="sRGB" renderer="colorManagement: true, physicallyCorrectLights" vr-mode-ui="enabled: false" device-orientation-permission-ui="enabled: false">
      <a-assets>
        <img id="card" src="../img/img_04.png" />
        <a-asset-item id="avatarModel" src="https://cdn.jsdelivr.net/gh/hiukim/mind-ar-js@1.2.5/examples/image-tracking/assets/card-example/softmind/scene.gltf"></a-asset-item>
      </a-assets>

      <a-camera position="0 0 0" look-controls="enabled: false"></a-camera>
      <a-entity mindar-image-target="targetIndex: 0">
        <a-plane color="blue" opaciy="0.5" position="0 0 0" height="0.552" width="1" rotation="0 0 0"></a-plane>
        <!-- <a-gltf-model rotation="0 0 0 " position="0 0 0.1" scale="0.005 0.005 0.005" src="#avatarModel" animation="property: position; to: 0 0.1 0.1; dur: 1000; easing: easeInOutQuad; loop: true; dir: alternate"></a-gltf-model> -->
      </a-entity>
    </a-scene>
  </body>
</html>

trips/templates/user_profile.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>使用者資訊</title>
    <style>
        /* 僅在手機上顯示 */
        @media (min-width: 481px) {
            body {
                display: none;
            }
        }

        @media (max-width: 480px) {
            body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 0;
                text-align: center; /* 所有文字置中 */
                background-image: url('https://github.com/tdance555/tdance2024/blob/main/media/vendor_icons/WebAR_Background.png?raw=true');  /* 背景圖像路徑 */
                background-size: 100% 100%; /* 使背景圖像覆蓋整個背景 */
                background-position: center center; /* 將背景圖像置中 */
                background-repeat: no-repeat; /* 防止背景圖像重複 */
            }

            .container {
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
                height: 100vh; /* 占滿視窗高度 */
                padding: 20px;
                box-sizing: border-box;
            }

            h1 {
                margin-bottom: 20px;
            }

            .gender-buttons {
                display: flex;
                justify-content: center;
                margin-bottom: 15px;
            }

            .gender-button {
                padding: 10px;
                margin: 5px;
                cursor: pointer;
                border: 1px solid #ccc; /* 按鈕邊框顏色 */
                border-radius: 5px;
                background-color: #f0f0f0; /* 按鈕默認背景顏色 */
                color: #333; /* 按鈕默認文字顏色 */
                font-size: 16px;
                outline: none;
                flex: 1; /* 按鈕平分容器寬度 */
                box-sizing: border-box;
            }

            .gender-button.selected {
                background-color: #4CAF50; /* 選中狀態的背景顏色 */
                color: white; /* 選中狀態的文字顏色 */
            }

            .form-group {
                margin-bottom: 15px;
                text-align: center; /* 文字置中 */
            }

            input[type="tel"] {
                width: 100%;
                padding: 10px;
                box-sizing: border-box;
                border: 1px solid #ccc; /* 輸入框邊框顏色 */
                border-radius: 5px;
            }

            button {
                width: 100%;
                padding: 10px;
                background-color: #4CAF50; /* 送出按鈕背景顏色 */
                color: white; /* 送出按鈕文字顏色 */
                border: none;
                border-radius: 5px;
                cursor: pointer;
                font-size: 16px;
                outline: none;
            }

            .text1 {
                font-size: 15pt;
            }

            .text2 {
                font-size: 10pt;
            }
        }
    </style>
    <!-- 引入intl-tel-input的CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/css/intlTelInput.css" />
</head>
<body>
    <div class="container">
        <h1 class="text1">在開始旅遊之前，我們想知道......</h1>
        <h2 class="text2">請提供簡單資訊方便我們紀錄您的集點資訊</h2>

        <form id="user-form" method="post" action="{% url 'user_profile' %}">
            {% csrf_token %}
            <div class="form-group">
                <h3>手機號碼</h3>
                <input type="tel" id="phone" name="phone" placeholder="輸入手機號碼">
            </div>
            <div class="form-group">
                <h3>性別</h3>
                <div class="gender-buttons">
                    <div class="gender-button" data-value="M">男</div>
                    <div class="gender-button" data-value="F">女</div>
                    <div class="gender-button" data-value="O">其他</div>
                </div>
                <input type="hidden" id="id_gender" name="gender" value="">
            </div>
            <button type="submit">送出</button>
        </form>
    </div>

    <!-- 引入intl-tel-input的JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/intlTelInput.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // 初始化intl-tel-input
            var input = document.querySelector("#phone");
            var iti = window.intlTelInput(input, {
                utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/utils.js",
                initialCountry: "TW" // 设置默认国家为台湾
            });

            // 處理性別按鈕點擊事件
            let buttons = document.querySelectorAll('.gender-button');
            buttons.forEach(function(button) {
                button.addEventListener('click', function() {
                    buttons.forEach(function(btn) {
                        btn.classList.remove('selected');
                    });
                    button.classList.add('selected');
                    document.getElementById('id_gender').value = button.dataset.value;
                });
            });

            // 處理表單提交事件
            document.getElementById('user-form').addEventListener('submit', function(event) {
                // 檢查手機號碼是否有效
                if (!iti.isValidNumber()) {
                    alert("請輸入有效的手機號碼");
                    event.preventDefault(); // 阻止表單提交
                } else {
                    // 將國際化的電話號碼設置為隱藏字段，以便後端處理
                    var hiddenPhoneInput = document.createElement("input");
                    hiddenPhoneInput.setAttribute("type", "hidden");
                    hiddenPhoneInput.setAttribute("name", "international_phone");
                    hiddenPhoneInput.setAttribute("value", iti.getNumber());
                    document.getElementById("user-form").appendChild(hiddenPhoneInput);

                    // 設置Cookie保存手機號碼
                    document.cookie = "phone=" + iti.getNumber() + "; path=/; max-age=" + (60 * 60 * 24 * 30); // 30天的過期時間
                }
                // 檢查是否選擇了性別
                if (document.getElementById('id_gender').value === '') {
                    alert("請選擇性別");
                    event.preventDefault(); // 阻止表單提交
                } else {
                    // 若一切正確，進行重定向
                    window.location.href = "{% url 'manual' %}";
                }
            });
        });
    </script>
</body>
</html>